### ISSUE TITLE
Python 3.5.2 - doesn't work

### ISSUE THREAD

**Issue by vabue** [gebvlad/bitrix24-python-sdk#1]
Hi, great initiative!

But it seems not working on fresh python:

```
#pip3 list |grep bitrix24
bitrix24-python-sdk (1.0.1)
#python3
Python 3.5.2 (default, Oct  1 2016, 13:12:23)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitrix24 import Bitrix24
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Bitrix24'
>>>
```

also if you'll try
```
python 3.5.2 (default, Oct  1 2016, 13:12:23)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitrix24 import bitrix24
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/bitrix24/bitrix24.py", line 9, in <module>
    from multidimensional_urlencode import urlencode
  File "/usr/local/lib/python3.5/site-packages/multidimensional_urlencode/__init__.py", line 1, in <module>
    from urlencoder import urlencode  # noqa
ImportError: No module named 'urlencoder'
```

*multidimensional_urlencode* is not yet python3 compatible. Is it necessary to form url parameters string? Because I see that B24 can get parameters inside POST body:

```
POST /rest/user.get.json HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 55
Content-Type: application/json
Host: ktc.bitrix24.ua
User-Agent: HTTPie/0.9.6

{
    "ID": "14",
    "auth": "myauth"
}

HTTP/1.1 200 OK
{
    "result": [
        {
            "ACTIVE": true,
            "EMAIL": "nospam@ktc.ua",
            "ID": "14",
            "LAST_NAME": "Будкин",
            "NAME": "Валентин",
        }
    ],
    "total": 1
}
```

**Comment by Nikovit** [comment]
on python 3.6 does not work

`>>> from bitrix24 import bitrix24
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\OneDrive\WORC\Python\bitrix24\.env\lib\site-packages\bitrix24\bitrix24.py", line 9, in <module>
    from multidimensional_urlencode import urlencode
  File "d:\OneDrive\WORC\Python\bitrix24\.env\lib\site-packages\multidimensional_urlencode\__init__.py", line 1, in <module>
    from urlencoder import urlencode  # noqa
ModuleNotFoundError: No module named 'urlencoder'
`

**Comment by yarbshk** [comment]
@Nikovit and @vabue, looks like you don't follow the [requirements](https://github.com/gebvlad/bitrix24-python-sdk#requirements).

**Comment by RomanKovtyukh** [comment]
@Nikovit, now multidimensional_urlencode works on python 3.6 too.
