### ISSUE TITLE
cannot import name 'Bitrix24' from 'bitrix24' 

### ISSUE THREAD

**Issue by vinni-pux** [gebvlad/bitrix24-python-sdk#4]
Hey guys, I have a problem with using this module after installation

```
PyDev console: starting.
Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)] on darwin

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/vinni/Documents/GitHub/test.py", line 2, in <module>
    from bitrix24 import Bitrix24
ImportError: cannot import name 'Bitrix24' from 'bitrix24' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bitrix24/__init__.py)

```

OS - MacOS 10.15
Python - 3.8

**Comment by kabilovtoha** [comment]
look at    https://github.com/gebvlad/bitrix24-python-sdk/pulls

**Comment by slntopp** [comment]
Same

**Comment by 81n90** [comment]
same
